# Generated by Django 5.1.2 on 2025-01-28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_videogenerationjob_final_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='videogenerationjob',
            name='progress_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]

