# Generated by Django 5.1.2 on 2025-12-12 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_videogenerationjob_progress_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='ABTestEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('impression', 'Impression'), ('click', 'Click')], max_length=20)),
                ('variant', models.CharField(choices=[('A', 'Variant A (kudos)'), ('B', 'Variant B (thanks)')], max_length=1)),
                ('session_id', models.CharField(db_index=True, max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event_type', 'variant'], name='web_abteste_event_t_cc7179_idx'), models.Index(fields=['session_id', 'created_at'], name='web_abteste_session_51fe96_idx')],
            },
        ),
    ]
